### ISSUE TITLE
org.springframework.web.client.HttpClientErrorException: 403 Forbidden

### ISSUE THREAD

**Issue by vamshi9700** [Hygieia/hygieia-scm-github-collector#11]
Hi,

I installed Hygieia (core,UI,api) on same machine with mongodb integration.

After configuring the Github collector i am running into below issue.

Note:I am using public Github repo url , so no credentials are provided.

Below  are my configurations:

application.properties:-

hygieia@ubuntu-VirtualBox:~/Hygieia/hygieia-scm-github-collector$ ls
application.properties  docker  Dockerfile  LICENSE  logs  MAINTAINERS  pom.xml  README.md  src  target
hygieia@ubuntu-VirtualBox:~/Hygieia/hygieia-scm-github-collector$ vi application.properties
# Database Name
        dbname=dashboarddb

        # Database HostName - default is localhost
        dbhost=localhost

        # Database Port - default is 27017
        dbport=27017

        # Database Username - default is blank
        dbusername=dashboarduser

        # Database Password - default is blank
        dbpassword=dbpassword

        # Proxy URL
        github.proxy=corporate proxt ipaddress

        # Proxy Port
        github.proxyPort=8080

        # Proxy user if auth is required
        github.proxyUser=XXXXXXX

        # Proxy password if auth is required
        github.proxyPassword=XXXXXXX

        # Logging File location
        logging.file=./logs/github.log

        # Collector schedule (required)
        github.cron=*/10 * * * * *

        github.host=github.com

api.properties:-

dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=localhost
dbport=27017

server.contextPath=/api
server.port=8080

Please help me in resolving this

2019-09-26 13:28:40,087 [taskScheduler-1] INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=, branch=master, userID=, url=https://github.com/Hygieia/Hygieia}::master:: get commits
2019-09-26 13:28:40,096 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/Hygieia/Hygieia/commits?sha=master&since=2019-09-26T13:18Z
2019-09-26 13:28:42,094 [taskScheduler-1] INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=, branch=master, userID=, url=https://github.com/Hygieia/Hygieia}::master get issues
2019-09-26 13:28:42,098 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/Hygieia/Hygieia/issues?state=all&since=2019-09-26T13:18Z
2019-09-26 13:28:42,430 [taskScheduler-1] INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=, branch=master, userID=, url=https://github.com/Hygieia/Hygieia}::master::get pulls
2019-09-26 13:28:42,458 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - Executing [https://api.github.com/repos/Hygieia/Hygieia/pulls?state=all&base=master&sort=updated&direction=desc
2019-09-26 13:28:44,611 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - pr 3142 WIP: multiple widgets
2019-09-26 13:28:45,915 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - pr 3151 Fix/add test-data for local testing UI. Add 5 type of dashboards on gener…
2019-09-26 13:28:46,901 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - pr 3135 TIR is not a valid CollectorType
2019-09-26 13:28:47,936 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - pr 3077 Changing Sonar's widget, lineCoverage to coverage
2019-09-26 13:28:49,074 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - pr 3139 version increment to 3.1.1-SNAPSHOT
2019-09-26 13:28:50,028 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - pr 3138 Fixed release issues of UI project and incremented the version
2019-09-26 13:28:50,990 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - pr 3137 updated SCM urls with Hygieia Organization
2019-09-26 13:28:52,163 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - pr 3136 removed the jenkins publisher plugin from script
2019-09-26 13:28:53,188 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - pr 3131 merge
2019-09-26 13:28:54,258 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - pr 3130 Remove api-audit collector post Migration
2019-09-26 13:28:55,240 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - pr 3129 Fix the issues with user logins
2019-09-26 13:28:56,280 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - pr 3124 Remove artifactory collector post Migration
2019-09-26 13:28:57,250 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - pr 3118 Revert "Get Karma unit tests working"
2019-09-26 13:28:58,361 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - pr 3119 Fixed the link to travis builds
2019-09-26 13:28:59,321 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - pr 2549 Feature to allow multiple widgets
2019-09-26 13:29:01,141 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - pr 3121 Test audit response with release build artifact info
2019-09-26 13:29:01,462 [taskScheduler-1] ERROR c.c.d.collector.GitHubCollectorTask - Error fetching commits for:https://github.com/Hygieia/Hygieia
org.springframework.web.client.HttpClientErrorException: 403 Forbidden
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCall(DefaultGitHubClient.java:597) ~[github-scm-collector-3.1.2-SNAPSHOT.jar!/:3.1.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultGitHubClient.getComments(DefaultGitHubClient.java:394) ~[github-scm-collector-3.1.2-SNAPSHOT.jar!/:3.1.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultGitHubClient.getPulls(DefaultGitHubClient.java:265) ~[github-scm-collector-3.1.2-SNAPSHOT.jar!/:3.1.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:221) ~[github-scm-collector-3.1.2-SNAPSHOT.jar!/:3.1.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.5.jar!/:3.1.2-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_221]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_221]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_221]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_221]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]
2019-09-26 13:29:01,483 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Repo Count              1       21s
2019-09-26 13:29:01,486 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - New Commits             0       21s
2019-09-26 13:29:01,487 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - New Pulls               0       21s
2019-09-26 13:29:01,491 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - New Issues              0       21s
2019-09-26 13:29:01,492 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Finished                        21s
2019-09-26 13:29:10,001 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Running Collector: GitHub
2019-09-26 13:29:10,021 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-09-26 13:29:10,021 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Starting...
2019-09-26 13:29:10,022 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-09-26 13:29:10,055 [taskScheduler-1] INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=, branch=master, userID=, url=https://github.com/Hygieia/Hygieia}::master:: get commits
2019-09-26 13:29:10,056 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/Hygieia/Hygieia/commits?sha=master&since=2019-09-26T13:18Z
2019-09-26 13:29:10,342 [taskScheduler-1] ERROR c.c.d.collector.GitHubCollectorTask - Error fetching commits for:https://github.com/Hygieia/Hygieia
org.springframework.web.client.HttpClientErrorException: 403 Forbidden
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCall(DefaultGitHubClient.java:597) ~[github-scm-collector-3.1.2-SNAPSHOT.jar!/:3.1.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultGitHubClient.getCommits(DefaultGitHubClient.java:99) ~[github-scm-collector-3.1.2-SNAPSHOT.jar!/:3.1.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:198) ~[github-scm-collector-3.1.2-SNAPSHOT.jar!/:3.1.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.5.jar!/:3.1.2-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_221]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_221]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_221]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_221]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]
2019-09-26 13:29:10,361 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Repo Count              1        0s
2019-09-26 13:29:10,362 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2019-09-26 13:29:10,368 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - New Pulls               0        0s
2019-09-26 13:29:10,370 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - New Issues              0        0s
2019-09-26 13:29:10,371 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Finished                         0s

**Comment by Sbrenthughes** [comment]
You'll need to generate a key for the API/Github properties to use. Next you'll likely need to generate a personal access token and pass that in from the UI
